### ISSUE TITLE
Doesn't compile on macos due to alsa

### ISSUE THREAD

**Issue by Muvkina** [torsteingrindvik/bevy-vfx-bag#71]
due to this line in the cargo toml: https://github.com/torsteingrindvik/bevy-vfx-bag/blob/debc1a5af06398c7e62e4efac3d9eb8b3fcc836a/Cargo.toml#L36. 

It won't compile on macos for now I just cloned into my project and changed it but would be nice to see an upstream fix if possible. Awesome crate!

**Comment by torsteingrindvik** [comment]
Thanks for the report.
I'll try adding a CI workflow which cross compiles before the next release.

**Comment by torsteingrindvik** [comment]
Removed the offending lines you mentioned.
So that should not be an issue in `main` now.

**Comment by Muvkina** [comment]
Awesome thanks! Out of curiosity why was it a dependency in the first place? Isn’t it a Linux audio library/backend? Not criticizing you all just would love to know if there was a reason considering this crate doesn’t deal with audio afaik

**Comment by torsteingrindvik** [comment]
I'm actually not sure either, if I remember correctly there was an issue where Bevy `main` was broken due to this stuff and it propagated down to this plugin. (EDIT: I found the fix by looking at what the maintainers were saying on Discord)
I either couldn't compile locally or on CI or both... but I agree, ALSA (or audio stuff in general) shouldn't be a part of this plugin's dependency tree.

Right now `[dev-dependencies]` use Bevy with default features on, so that will bring in audio as a dep for sure.
An optimization for a day with little else to do could be to only enable the features actually needed for examples too.

**Comment by Muvkina** [comment]
Interesting! Again no worries was just honestly curious thanks for getting it fixed in main
